sudo: required
services:
  - docker

before_install:
  - docker build -t akshay2000saxena/docker-react -f Dockerfile.dev .

script:

  - docker run akshay2000saxena/docker-react npm run test -- --coverage